services:
  - type: static
    name: sms-blossom-frontend
    envVars:
      - key: VITE_BACKEND_URL
        sync: false   # set in Render dashboard
      - key: VITE_SHOPIFY_API_KEY
        sync: false   # set in Render dashboard (optional)
    buildCommand: npm ci && npm run api:generate && npm run build && node scripts/check-build.js
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
