# sms-blossom-frontend/shopify.app.toml

client_id = "47aa6b9af3382b1ae6ac67f179409f97"
name = "sms-blossom"
embedded = true

# Deployed frontend on Render (replace with your actual domain)
application_url = "https://sms-blossom-frontend.onrender.com"

[build]
# Το CLI θα αντικαθιστά τα URLs με το dev tunnel όταν τρέχεις `shopify app dev`
automatically_update_urls_on_dev = true

# OAuth παραμένει στο backend (Express)
[auth]
redirect_urls = [
  "https://sms-blossom-api.onrender.com/auth/callback"
]

# App Proxy → backend (όπως το έχεις)
[app_proxy]
url = "https://sms-blossom-api.onrender.com/public"
subpath = "sms-blossom"
prefix = "apps"

[webhooks]
api_version = "2025-10"

[access_scopes]
scopes = "read_customers,write_customers,read_discounts,write_discounts,read_inventory,read_orders"
